### ISSUE TITLE
Updates for Fedora 26/27

### ISSUE THREAD

**Issue by drewofdoom** [ycollet/fedora-spec#1]
This repo is rather old at this point. Fedora 27 is due for release on October 30.

I have tested many of the SPECS already and they build without issue on 26. Drumgizmo, however, is missing libsmf-devel and will not build.

**Comment by ycollet** [comment]
Thanks for these tests.
I have a spec file for libsmf-devel.
The only problem I've got is the the CCRMA repo is not totally filed with packages.
The Kernel RT package has been available only one month ago. 
SuperCollider is still missing and is required for sonic-pi.
I will generate the Fedora 26 / 27 repos without this problematic packages this week. And I will manage to build the missing CCRMA packages myself.

Best regards,

Yann

**Comment by ycollet** [comment]
The repo is now ready (sonic-pi still building, but all the other packages are ready).
