### ISSUE TITLE
Add ultranova4linux

### ISSUE THREAD

**Issue by Baggypants** [ycollet/fedora-spec#13]
I wrote a spec file for ultranova4linux ages ago and it would make more sense to put it in your copr than me keep it in mine

https://gitlab.com/spec-files-for-various-rpms/spec-files-for-various-rpms/-/tree/master/ultranova4linux

https://therobinsonfamily.net/SRPMS/ultranova4linux-0.0-4.20160101git25b76aa0.fc29.src.rpm

**Comment by ycollet** [comment]
Thank's a lot. Il will add the spec file ASAP !

**Comment by ycollet** [comment]
Just add here with some modifs.
with these changes, I can get the Source0 file by spectool -g ultranova.spec
