### ISSUE TITLE
loudness-scanner should not include libebur128

### ISSUE THREAD

**Issue by markk** [ycollet/fedora-spec#15]
libebur128 is packaged in the fedora repos and is a dependent package of e.g. shotcut. Thus trying to install loudness-scanner gets the error:

```
Error: Transaction test error:
  file /usr/lib64/libebur128.so.1 from install of loudness-scanner-0.5.1-1.fc32.x86_64 conflicts with file from package libebur128-1.2.4-3.fc32.x86_64
```

Could loudness-scanner depend on rather than include libebur128?

**Comment by ycollet** [comment]
Thanks for the report. I will try to fix that ASAP ..

**Comment by ycollet** [comment]
Can you try the updated package ?

**Comment by markk** [comment]
Thanks! Looks like the executables have not been installed correctly...

```
$ ls -l /usr/bin/loudness*
-rw-r--r--. 1 root root  683096 May 28 10:30 /usr/bin/loudness
-rw-r--r--. 1 root root  729848 May 28 10:30 /usr/bin/loudness-drop-gtk
-rw-r--r--. 1 root root 1448736 May 28 10:30 /usr/bin/loudness-drop-qt
```

Once I made them executable, however:

```
$ loudness scan test.wav
Warning: no plugins found!
```

I think the files from https://github.com/jiixyj/loudness-scanner/tree/master/scanner/inputaudio need to be built and installed also.

**Comment by ycollet** [comment]
OK. Thanks for the report. I try to fix that ASAP.

**Comment by ycollet** [comment]
Fixed.
I tested the tool after the rpm build:
```
$ loudness scan 28_141986__stomachache__gong-rumble.wav
  Loudness                                                                      
-16.8 LUFS, 28_141986__stomachache__gong-rumble.wav
-------------------------------------------------------------------------------
-16.8 LUFS
```
The build is running ...

**Comment by ycollet** [comment]
Under Fedora 32, the gstreamer plugin is not compiled because loudscanner must be ported to the latest version of gstreamer. The mpg123 and sndfile plugins are compied.
On Fedora 30 and 31 all the 3 plugins are compiled.
If you need the ffmpeg plugin, tell me because ffmpeg is in the rpmfusion repo.

**Comment by markk** [comment]
Brilliant, thanks! All working. The sndfile plugin does all I need.
