### ISSUE TITLE
Dragonfly Reverb missing 2 reverbs

### ISSUE THREAD

**Issue by tassyv** [ycollet/fedora-spec#16]
the 3.1.1 package of Dragonfly Reverb only contains the Hall and Room Reverbs whereas the source and binariy tarballs on the original project's GitHub also contain Plate and EarlyReflection reverbs.

**Comment by ycollet** [comment]
thansk for the report.
That's odd because rpm check for unpackaged files when you use rpmbuild.
I will check that this afternoon.
I'll keep you informed.

**Comment by ycollet** [comment]
You where right. I fixed all this in the package currently building ...

**Comment by ycollet** [comment]
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/build/1448567/

Tell me if it fixes your problem.
I will then close the bug.

**Comment by tassyv** [comment]
Yep, that looks ok now, thanks for the quick fix !

**Comment by ycollet** [comment]
Thanks. I close the bug.
