### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by tyty999** [ycollet/fedora-spec#18]
Can you at least explain what is federa-spec and how to use it?

where can I download them if I don't use Fedora distro.

**Comment by ycollet** [comment]
If you use a red hat derivative, you can rebuild the rpm packages from the spec file.
Most of the time, you can copy the <package>.spec file in your rpmbuild/SPEC directory. 
Some times, there are some sources package to copy in rpmbuild/SOURCE directory.
After that: spectool -g <package>.spec in rpmbuild/SPEC. This command will download the some required source files. You must then move the downloaded files from rpmbuild/SPEC to rpmbuild/SOURCE.
And now, it's time to build the package:
rpmbuild -ba <package>.spec
The package to be manually installed via dnf / yum or rpm are located in rpmbuild/RPMS

I will try to add some informations in the README file ASAP.

**Comment by ycollet** [comment]
Done with 591a08dfc8c66ba6ce65cd0aaae83655c24120b7
