### ISSUE TITLE
breeze-icon-theme is requested when starting zrythm

### ISSUE THREAD

**Issue by BrunoVernay** [ycollet/fedora-spec#19]
I had to do `sudo dnf install breeze-icons` because I had a error message wen starting zrythm.

**Comment by ycollet** [comment]
Thanks for the report.
I will add breeze as a dependency for the next release of zrythm.

**Comment by ycollet** [comment]
The problem should be fixed with the last build ... Only available on Fedora 32 and 33. Too complicated to make it builds on Fedora 31.

**Comment by BrunoVernay** [comment]
Not yet :-)

1. I uninstalled `zrythm` and  `breeze-icon-theme` 
2. I installed `sudo dnf install zrythm`
```
Installed:
  libcyaml-1.1.0-1.fc32.x86_64        libreproc-14.2.0-1.fc32.x86_64        zrythm-1.0.0.a401-3.fc32.x86_64       
```
No installation errors, but it did not install `breeze-icon-theme`

3. When I start ZRythm, it complains about missing icons (same error)

**Comment by ycollet** [comment]
Damned !
I added a Require: breeze-icon-theme but, I don't know why yer, from time to time, the require doesn't work.
I will fix this fot the next build ...

**Comment by BrunoVernay** [comment]
and with version 1.0.0.a401-4.fc32 ... It works
Thanks !

**Comment by ycollet** [comment]
Thanks for the tests !
