### ISSUE TITLE
This Surge folder in Odin2's spec file look suspect

### ISSUE THREAD

**Issue by BrunoVernay** [ycollet/fedora-spec#20]
https://github.com/ycollet/fedora-spec/blob/5e860c169545cd45ea2ad9dbda595c50feb68a26/odin2/odin2.spec#L60

I found it searching for Surge.  It is not related to any issue.

**Comment by ycollet** [comment]
Thanks for the report. 
I used the surge spec file to build odin2. This .loca/share/Surge directory is an "intermediate" directory. I will rename it to fix the problem.

**Comment by ycollet** [comment]
fixed.
