### ISSUE TITLE
Ardour requires VST3 plugins to be in  XXX.vst3/Contents/x86_64-linux/XXX.so

### ISSUE THREAD

**Issue by BrunoVernay** [ycollet/fedora-spec#21]
https://github.com/ycollet/fedora-spec/blob/c61791761863741f1df8c8db4e3f8f561c2753c8/surge/surge.spec#L81

I installed both vst3-Surge and vst3-Stocha, but in Ardour 6.5.0 they are not discovered.

I had to
```
sudo mkdir -p Surge.vst3/Contents/x86_64-linux
sudo mv Surge.so Surge.vst3/Contents/x86_64-linux/ 
```
... to make them work in Ardour 6.5.0.

(Note: VST3 support in Ardour is very new. Maybe it is an Ardour limitation that will be solved in next version.)

**Comment by ycollet** [comment]
Ah, yes ! Thanks.
I totally forgot to fix the install directory of the vst3 plugin.
I tested a lot with odin2 to discover how a vst3 plugon is installed and forgot to fix surge and stochas ...

**Comment by ycollet** [comment]
I hope this is now fixed for surge and stochas

**Comment by BrunoVernay** [comment]
By the way, it would be helpful to have an alias like "surge-vst3", if it is easy to do.
I would be able to type `dnf install surge[Tab]` and it would display `surge` and `surge-vst3` ...

**Comment by ycollet** [comment]
Yes, this is the case with lv2 packages. They are prefixed with lv2-. Il will check all the vst packages and add the vst3- prefix.

**Comment by BrunoVernay** [comment]
Updated, both VST3  Surge and Stochas works perfectly. Thanks.  

The name `vst3-surge` already exists.  My point was eventually to create an alias `surge-vst3`  to find all `surge*` related packages.
