### ISSUE TITLE
klystrack: 2 different desktop files with same name

### ISSUE THREAD

**Issue by jn64** [ycollet/fedora-spec#27]
klystrack package makes 2 desktop files for klystrack-jack and klystrack-pulse, but the name is the same.

```
[Desktop Entry]
Name=Klystrack
```

so it shows up in GUI menus (e.g. GNOME launcher) as same.

**Comment by ycollet** [comment]
Oups ... Thanks for the report.
I'll fix this ASAP

**Comment by jn64** [comment]
Thanks! :)

I don't want to spam issues but I found another one. 

helio-workstation package makes the binary at `/usr/bin/Helio` (uppercase H), but desktop file has `Exec=/usr/bin/helio`. So the desktop file is hidden by GNOME because of invalid exec path.

**Comment by ycollet** [comment]
Thanks for the second report. I will fix this too ASAP.
For klystrack, it's fixed: $ dnf --refresh update

**Comment by ycollet** [comment]
I reported the bug upstream for helio.
The spec file is updated and the new build is running for Fedora 33 and 34.

**Comment by jn64** [comment]
Thanks!
