### ISSUE TITLE
BespokeSynth missing .desktop file

### ISSUE THREAD

**Issue by jn64** [ycollet/fedora-spec#28]
Package: BespokeSynth-1.0.0-5.fc33.x86_64

The upstream repo has a [BespokeSynth.desktop file](https://github.com/awwbees/BespokeSynth/blob/v1.0.0/BespokeSynth.desktop)

**Comment by ycollet** [comment]
OK, thanks for the report.
I will fix that  ASAP.

**Comment by ycollet** [comment]
Should be fixed now.

**Comment by jn64** [comment]
Thanks!
