### ISSUE TITLE
Missing dependency on Carla: python3-PyQt5

### ISSUE THREAD

**Issue by BrunoVernay** [ycollet/fedora-spec#4]
After installing Carla on Fedora 27:
```
carla
Traceback (most recent call last):
  File "/usr/share/carla/carla", line 22, in <module>
    from carla_host import *
  File "/usr/share/carla/carla_host.py", line 28, in <module>
    from PyQt5.QtCore import qCritical, QFileInfo, QModelIndex, QPointF, QTimer
ModuleNotFoundError: No module named 'PyQt5'
```
First I installed `PyQt5`, but that would have been too simple.

One has to install `sudo dnf install python3-PyQt5`.

If I knew where to put dependencies in a spec file, I would have made a PR.

**Comment by ycollet** [comment]
Hello,

Thanks for the report.
In the spec file, there are BuildRequires (requirements only for build) and Requires (runtime requirements).
Here, it looks like the Requires python3-PyQt5 is missing.
I will fix and rebuild the carla package ASAP.

Best regards,

Yann

**Comment by ycollet** [comment]
A new package has been published:

https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/build/678262/

**Comment by ycollet** [comment]
The problem is still present ...

**Comment by BrunoVernay** [comment]
It is precisely `python3-PyQt5`

**Comment by ycollet** [comment]
It's also a problem of spec syntax: "Requires:" is not enough. "Requires(pre):".
The spec doc sucks for this part ...

----- Mail original -----
De: "Bruno Vernay" <notifications@github.com>
À: "ycollet/fedora-spec" <fedora-spec@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "State change" <state_change@noreply.github.com>
Envoyé: Mercredi 22 Novembre 2017 15:42:41
Objet: Re: [ycollet/fedora-spec] Missing dependency on Carla: python3-PyQt5 (#4)



It is precisely python3-PyQt5

**Comment by ycollet** [comment]
A tested package has been built:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/build/678270/
