### ISSUE TITLE
Add licensing info to the .specs or the repo (if possible)

### ISSUE THREAD

**Issue by fpesari** [ycollet/fedora-spec#8]
Hello,

I am the co-maintainer for a sister project on openSUSE, Geekos DAW ([OBS repo](https://build.opensuse.org/project/show/home:geekositalia:daw)) and we might benefit a lot from exchanging `.specs`, however there is no licensing info in this repo so we can't use them (on the contrary, we try to keep all our specs under a free license, so feel free to take anything you want from them).

Could you please release them under a FSF or OSI compliant license? If so, we will be able to use your specs and of course, you (and other contributors to this repo who agree with it) will be credited in the copyright notice. Thank you! :smiley_cat:

**Comment by ycollet** [comment]
Thanks a lot for this message.
I just uploaded a GPL3 License file.
When I created the repo, I selected this license, but I forgot to upload the licence file.
I just has a look at your repo. Nice. I will certainly adapt some of your spec file to this repo.
Feel free to use some of my spec files !
Best regards,
YC
