### ISSUE TITLE
picoloop

### ISSUE THREAD

**Issue by Baggypants** [ycollet/fedora-spec#9]
I tried installing picoloop but I hit a few issues

1) the picoloop bin isn't executable
2) it's missing SDL2_ttf as a dependency
3) I can't get it to run.

**Comment by ycollet** [comment]
Thanks a lot for the report.
On which version of Fedora do you run picoloop ?
I just have updated picoloop to 0.77e on Fedora 29 / 30.
Does this version works for you ?

**Comment by Baggypants** [comment]
It still isn't executable 

```
[baggypants@swordfish2 ~]$ picoloop
bash: /usr/bin/picoloop: Permission denied
[baggypants@swordfish2 ~]$ ls -l /usr/bin/picoloop
-rw-r--r--. 1 root root 31876048 Sep 29 17:50 /usr/bin/picoloop
```

**Comment by ycollet** [comment]
Argh ...

Can you try a "chmod a+x /usr/bin/picoloop" as a root user and then try to start the application ?
On my side, it works ...

I will check on my side if there is a problem in the spec file.

Best regards 

YC

**Comment by Baggypants** [comment]
This is what it does when I run it after correcting the permissions
```
[baggypants@swordfish2 ~]$ picoloop

MidiOutDummy: This class provides no functionality.


MidiInDummy: This class provides no functionality.

joystick not connected!
```

Then it instantly quits.

**Comment by Baggypants** [comment]
I'm using f30

**Comment by ycollet** [comment]
I just installed F30 (I was on F28).
I  will try to reproduce the problem on my machine

**Comment by ycollet** [comment]
I just uploaded a new package for picoloop.
The GUI shows up now, but on my side, I am still now able to get sound.
The gui freezes because picoloop can't connect to the alsa driver ...

**Comment by ycollet** [comment]
I just fixed the problem.
Now, in the picoloop package, there are 3 binaries:
- picoloop-alsa 
- picoloop-pulse
- picoloop-jack
I started picoloop-pulse and the interface shows up without freezing.
I also installed a pdf file in /usr/share/picoloop/documentation

**Comment by Baggypants** [comment]
I got picoloop-jack working fine. Super job!

**Comment by ycollet** [comment]
OK, I close the bug.
Thanks a lot for you comment :)
